name: C++ Windows Build (MinGW)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MinGW-w64
      # This action sets up a MinGW environment, including g++.
      uses: egor-timoshenko/setup-mingw@v1
      with:
        version: 'latest' # You can specify a version like '12.2.0' if needed

    - name: List files (for debugging - optional)
      run: dir

    - name: Compile with MinGW-w64 (g++)
      run: g++ main.cpp -o SignatureKid.exe

    - name: Run compiled program (optional - for testing)
      run: .\SignatureKid.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SignatureKid-windows-mingw
        path: SignatureKid.exe
