name: Build on Windows (MinGW)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-mingw:
    runs-on: windows-latest # Use the latest Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW-w64 via MSYS2
      # We'll use pacman (available in MSYS2, which is pre-installed on Windows runners)
      # to install the MinGW-w64 toolchain.
      # The 'msys2 {0}' syntax is a special way to run commands within the MSYS2 environment.
      run: |
        pacman -S --noconfirm --needed mingw-w64-x86_64-toolchain
      shell: msys2 {0} # This ensures commands run in the MSYS2 bash environment

    - name: Add MinGW to PATH
      # This step explicitly adds the MinGW bin directory to the PATH
      # for subsequent steps in the job.
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
      shell: bash # Use bash for path manipulation

    - name: Compile C++ code
      run: |
        # Now g++ should be available because we added its path
        g++ main.cpp -o SignatureKid.exe
      shell: bash # Use bash for compilation

    - name: Run compiled executable (optional)
      run: ./SignatureKid.exe
      shell: bash

    - name: Upload artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: SignatureKid-Windows-MinGW
        path: SignatureKid.exe
