name: Build C++ Executable

on: [push, pull_request]  # Triggers on push/PR

jobs:
  build:
    runs-on: windows-latest  # Windows required for .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW
      run: choco install mingw -y
    - name: Compile
      run: g++ main.cpp -o output.exe
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Executable
        path: output.exe
