name: C++ Windows Build (MSVC)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC environment
      # The vswhere action helps locate and set up the Visual Studio environment.
      # While windows-latest often has paths set, this is more robust.
      uses: microsoft/setup-msbuild@v2

    - name: List files (for debugging - optional)
      run: dir

    - name: Compile with MSVC
      run: cl main.cpp /Fe:SignatureKid.exe
      # /Fe: specifies the output executable name

    - name: Run compiled program (optional - for testing)
      run: .\SignatureKid.exe
      # Use `.\` to run executables in PowerShell/Cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SignatureKid-windows
        path: SignatureKid.exe
