name: Build on Windows (MinGW)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-mingw:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2 and Install MinGW-w64 toolchain
      run: |
        C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
        C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm --needed mingw-w64-x86_64-toolchain"
      shell: powershell

    - name: Add MinGW to PATH
      run: |
        $env:Path += ";C:\msys64\mingw64\bin"
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Verify g++ is available (optional)
      run: g++ --version
      shell: powershell

    - name: Compile C++ code
      run: |
        g++ main.cpp -o SignatureKid.exe
      shell: powershell

    - name: Run compiled executable (optional)
      # *** IMPORTANT CHANGE HERE ***
      # Provide dummy arguments for testing your program's argument parsing.
      # Replace 'dummy_signed_src_path.exe' and 'dummy_target_path.exe'
      # with actual paths you might want to test against, if applicable.
      run: .\SignatureKid.exe D:\a\SignatureKid\SignatureKid\kernel32.dll D:\a\SignatureKid\SignatureKid\creed.exe
      shell: powershell

    - name: Upload artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: SignatureKid-Windows-MinGW
        path: SignatureKid.exe
