name: Build on Windows (MinGW)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-mingw:
    runs-on: windows-latest # Use the latest Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2 and Install MinGW-w64 toolchain
      # Use a direct approach to interact with MSYS2.
      # The GitHub Actions Windows runners typically have MSYS2 pre-installed.
      # We need to run pacman commands inside its environment.
      run: |
        # Update MSYS2 packages
        C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
        # Install the MinGW-w64 toolchain
        C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm --needed mingw-w64-x86_64-toolchain"
      shell: powershell # Use PowerShell to execute the bash commands within MSYS2

    - name: Add MinGW to PATH
      # The MinGW tools are typically found in C:\msys64\mingw64\bin after installation
      run: |
        $env:Path += ";C:\msys64\mingw64\bin"
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell # Use PowerShell for Windows path manipulation

    - name: Verify g++ is available (optional)
      run: g++ --version
      shell: powershell

    - name: Compile C++ code
      run: |
        g++ main.cpp -o SignatureKid.exe
      shell: powershell # Use PowerShell for compilation

    - name: Run compiled executable (optional)
      run: .\SignatureKid.exe
      shell: powershell

    - name: Upload artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: SignatureKid-Windows-MinGW
        path: SignatureKid.exe
